name: Upload build artifact
description: Upload build artifact

runs:
  using: composite
  steps:
  - name: Prepare build artifact
    shell: bash
    run: |
      set -eux
      find . -type d -name build -print | xargs tar --zstd -cf build.tar.zstd .gradle

  - name: Upload build artifact
    uses: actions/upload-artifact@v4
    with:
      name: Build
      path: build.tar.zstd
      retention-days: 1
